### ISSUE TITLE
Moving to center stopped working correctly in KDE Plasma 5.27.3

### ISSUE THREAD

**Issue by denilsonsa** [Merrit/kwin-move-window#3] opened 2023-04-04 08:06 UTC
When using a mix of display resolutions and orientations, the "move to center" doesn't work correctly anymore. At best, the window position will be off center. At worst, it will be outside the visible area (i.e. in the dead area above the left-most display in the next picture).

This happens on any action that calculates the center position (either vertically or horizontally or both).

![Screenshot_20230404_095735](https://user-images.githubusercontent.com/121676/229726884-679705fd-3704-4cf7-be0a-531791c3f680.png)

When I used only the two vertical displays, the bug seemed gone.

This is a regression, it's new to this KDE Plasma version 5.27.3, recently made available for Manjaro users.

It is likely this is an upstream bug. I'm not sure yet, and also not sure to which module I should report it. (EDIT: I went ahead and [reported it to KDE](https://bugs.kde.org/show_bug.cgi?id=468260).)

It's also possible that for some unknown reason this is a transient bug that can go away after I reboot. I don't know this yet, I wanted to report this bug as soon as I found it.

**Comment by Merrit** [comment] 2024-03-22 18:14
Hey, sorry about the delay - no idea how I wasn't notified of this issue.

There have been several changes related to this sort of code, and now the script has been further migrated to Plasma 6. Is this still an issue for you?

**Comment by denilsonsa** [comment] 2024-03-23 07:20
I haven't upgraded the script to the latest version because I'm afraid it might not work on Plasma 5.27.11.

Also, for the past months I have not used a multi-monitor setup that has a hole. And I don't have time to test it right now. Maybe next week I can try, but it would also be appreciated if you could try reproducing it yourself. But I know it was an issue even after rebooting.

**Comment by Merrit** [comment] 2024-03-23 15:10
I use multiple displays with different resolutions, but they don't rotate. I haven't noticed any issue like this for some time, myself.

[v1.0.2](https://github.com/Merrit/kwin-move-window/releases/tag/v1.0.2) is the latest version that supports Plasma 5, versions after that only support Plasma 6.

**Comment by Merrit** [comment] 2024-04-06 20:43
I'm going to close this for now since I can't reproduce it, but if you experience the issue again feel free to reopen! :)

**Closed as completed by Merrit** 2024-04-06 20:43 UTC

**Comment by denilsonsa** [comment] 2024-04-07 09:18
I finally had some time, and I decided to give it a try.

If I update it using Discover or the built-in KDE/Plasma "Get New Scripts" dialog, it will install v1.1.1 which only works for Plasma 6 and doesn't work on Plasma 5. I don't know why, I did not investigate.

Then, I manually replaced the contents of `~/.local/share/kwin/scripts/movewindow/*` with the contents of [v1.0.2](https://github.com/Merrit/kwin-move-window/tree/v1.0.2). I disabled the plugin, hit Apply, closed the settings manager, opened it again, re-enabled the plugin, hit apply. Now I know for sure the 1.0.2 version is running. (Although it claims to be v1.0.0 because you accidentally forgot to update the version in the metadata file, oops!). And now it seems to work fine.

So, I believe it's fixed now. Thanks! Maybe worth making sure people will download the right version for their desktop from the KDE store, but I'll leave this up to you.

**Comment by Merrit** [comment] 2024-04-07 14:02
Great, thanks for confirming!

> Although it claims to be v1.0.0 because you accidentally forgot to update the version in the metadata file, oops!).

Yeah, oops! :sweat_smile: 

As for preventing the update to a non-supported version, I don't see any way to do so sadly - the script metadata doesn't have a field to specify which versions of KWin it supports, and the Pling store doesn't have a way to do so either. A big oversight for both of them, and I don't see any way I can prevent automatic updates until it is resolved in one of those 2 places. :/

**Comment by Merrit** [comment] 2024-04-07 14:12
I added it to my to-do list for my KDE Developer tasks, when I have some time will look into adding such a field to the KWin scripting API.
